workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      groups:
        - keystore # <-- (Includes CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS)
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
        PACKAGE_NAME: 'io.codemagic.marijan.flutterlinux' # <-- Put your package name here e.g. "io.codemagic.flutteryaml"
        GOOGLE_PLAY_TRACK: 'internal' # <-- Any default or custom track that is not in ‘draft’ status
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Check Build Number
        script: |
          echo $BUILD_NUMBER
          echo $PROJECT_BUILD_NUMBER
      - name: Set up key properties
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Build APK with Flutter
        script: |
          export LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name '$PACKAGE_NAME')
          cd . && flutter build appbundle --release
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
#    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/yaml-publishing/email
      #      email:
      #        recipients:
      #          - user_1@example.com
      #          - user_2@example.com
      #        notify:
      #          success: true # To receive a notification when a build succeeds
      #          failure: false # To not receive a notification when a build fails
      #      slack:
      #        # See the following link about how to connect your Slack account - https://docs.codemagic.io/yaml-publishing/slack
      #        channel: '#builds'
      #        notify_on_build_start: true # To receive a notification when a build starts
      #        notify:
      #          success: true # To receive a notification when a build succeeds
      #          failure: false # To not receive a notification when a build fails
#      google_play:
#        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#        track: $GOOGLE_PLAY_TRACK
#        in_app_update_priority: 0
#        submit_as_draft: true